services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: bds-namenode
    restart: unless-stopped
    ports:
      - "9870:9870"
      - "9000:9000"
    env_file:
      - ./docker/hdfs/hadoop.env
    environment:
      CLUSTER_NAME: bds-hdfs

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: bds-datanode
    restart: unless-stopped
    ports:
      - "9864:9864"
    env_file:
      - ./docker/hdfs/hadoop.env
    environment:
      SERVICE_PRECONDITION: namenode:9870
    depends_on:
      - namenode
